#!/usr/bin/env python3.7
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 11 13:26:04 2018

@author: ejreidelbach

:DESCRIPTION:
    - Day 10 challenge 
        * https://adventofcode.com/2018/day/10

    ****** PART 1 ******
    For example, suppose you note the following points:
        
        position=< 9,  1> velocity=< 0,  2>
        position=< 7,  0> velocity=<-1,  0>
        position=< 3, -2> velocity=<-1,  1>
        position=< 6, 10> velocity=<-2, -1>
        position=< 2, -4> velocity=< 2,  2>
        position=<-6, 10> velocity=< 2, -2>
        position=< 1,  8> velocity=< 1, -1>
        position=< 1,  7> velocity=< 1,  0>
        position=<-3, 11> velocity=< 1, -2>
        position=< 7,  6> velocity=<-1, -1>
        position=<-2,  3> velocity=< 1,  0>
        position=<-4,  3> velocity=< 2,  0>
        position=<10, -3> velocity=<-1,  1>
        position=< 5, 11> velocity=< 1, -2>
        position=< 4,  7> velocity=< 0, -1>
        position=< 8, -2> velocity=< 0,  1>
        position=<15,  0> velocity=<-2,  0>
        position=< 1,  6> velocity=< 1,  0>
        position=< 8,  9> velocity=< 0, -1>
        position=< 3,  3> velocity=<-1,  1>
        position=< 0,  5> velocity=< 0, -1>
        position=<-2,  2> velocity=< 2,  0>
        position=< 5, -2> velocity=< 1,  2>
        position=< 1,  4> velocity=< 2,  1>
        position=<-2,  7> velocity=< 2, -2>
        position=< 3,  6> velocity=<-1, -1>
        position=< 5,  0> velocity=< 1,  0>
        position=<-6,  0> velocity=< 2,  0>
        position=< 5,  9> velocity=< 1, -2>
        position=<14,  7> velocity=<-2,  0>
        position=<-3,  6> velocity=< 2, -1>

    Each line represents one point. Positions are given as <X, Y> pairs: 
    X represents how far left (negative) or right (positive) the point appears, 
    while Y represents how far up (negative) or down (positive) the point 
    appears.

    At 0 seconds, each point has the position given. Each second, each point's 
    velocity is added to its position. So, a point with velocity <1, -2> is 
    moving to the right, but is moving upward twice as quickly. If this point's 
    initial position were <3, 9>, after 3 seconds, its position would 
    become <6, 3>.

    Over time, the points listed above would move like this:

        Initially:
        ........#.............
        ................#.....
        .........#.#..#.......
        ......................
        #..........#.#.......#
        ...............#......
        ....#.................
        ..#.#....#............
        .......#..............
        ......#...............
        ...#...#.#...#........
        ....#..#..#.........#.
        .......#..............
        ...........#..#.......
        #...........#.........
        ...#.......#..........
        
        After 1 second:
        ......................
        ......................
        ..........#....#......
        ........#.....#.......
        ..#.........#......#..
        ......................
        ......#...............
        ....##.........#......
        ......#.#.............
        .....##.##..#.........
        ........#.#...........
        ........#...#.....#...
        ..#...........#.......
        ....#.....#.#.........
        ......................
        ......................
        
        After 2 seconds:
        ......................
        ......................
        ......................
        ..............#.......
        ....#..#...####..#....
        ......................
        ........#....#........
        ......#.#.............
        .......#...#..........
        .......#..#..#.#......
        ....#....#.#..........
        .....#...#...##.#.....
        ........#.............
        ......................
        ......................
        ......................
        
        After 3 seconds:
        ......................
        ......................
        ......................
        ......................
        ......#...#..###......
        ......#...#...#.......
        ......#...#...#.......
        ......#####...#.......
        ......#...#...#.......
        ......#...#...#.......
        ......#...#...#.......
        ......#...#..###......
        ......................
        ......................
        ......................
        ......................
        
        After 4 seconds:
        ......................
        ......................
        ......................
        ............#.........
        ........##...#.#......
        ......#.....#..#......
        .....#..##.##.#.......
        .......##.#....#......
        ...........#....#.....
        ..............#.......
        ....#......#...#......
        .....#.....##.........
        ...............#......
        ...............#......
        ......................
        ......................

    After 3 seconds, the message appeared briefly: HI. Of course, your message 
    will be much longer and will take many more seconds to appear.

    What message will eventually appear in the sky?
    
    ****** PART 2 ******

"""
 
#==============================================================================
# Package Import
#==============================================================================
import os
import pandas as pd
import pathlib

#==============================================================================
# Function Definitions / Reference Variable Declaration
#==============================================================================
def ingestInput(file_input):
    '''
    Purpose: Ingest data given a specific filename or filepath

    Input: 
        (1) file_input (string): Filename of data for part 1 challenge
    
    Output: 
        (1) The data for the day's challenge (input.txt) in the folder /XX/ 
                where XX represents the day of the challenge (e.g. 05, 23)
    '''
    with open(file_input, 'r') as f:
        content = f.readlines()
        
    # Strip trailing new line from strings in the list
    for item in content:
        content[content.index(item)] = item.strip()
    
    return content

def functionName(var1, var2, var3):
    '''
    Purpose: Stuff goes here

    Input:   
        (1) var1 (type): description
        (2) var2 (type): description
        (3) var3 (type): description
    
    Output: 
        (1) output1 (type): description
    '''
#==============================================================================
# Working Code
#==============================================================================

# Set the project working directory
path_project = pathlib.Path('/home/ejreidelbach/Projects/adventOfCode2018')
os.chdir(path_project)

# Set the day of the project
day = '10'

# Download and ingest the data for today's challenge
data_raw = ingestInput(path_project.joinpath(day.zfill(2), 'input.txt'))

#------------------------------------------------------------------------------
# Part 1. What message will eventually appear in the sky?
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Part 2.
#------------------------------------------------------------------------------